export const UPDATE_MOBILE_ITEMS = 'UPDATE_MOBILE_ITEMS';
export const UPDATE_WEBSITE_ITEMS = 'UPDATE_WEBSITE_ITEMS';
export const UPDATE_WEBPLAIN = 'UPDATE_WEBPLAIN';
export const UPDATE_MOBPLAIN = 'UPDATE_MOBPLAIN';
export const TOGGLE_PWD_SHOW = 'TOGGLE_PWD_SHOW';
