export const UPDATE_MOBILE_ITEMS = 'UPDATE_MOBILE_ITEMS';
export const UPDATE_MOBDIFF = 'UPDATE_MOBDIFF';
export const UPDATE_WEBSITE_ITEMS = 'UPDATE_WEBSITE_ITEMS';
export const UPDATE_WEBDIFF = 'UPDATE_WEBDIFF';
