export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_CHAINID = 'UPDATE_CHAINID'
export const UPDATE_RDRAWER = 'UPDATE_RDRAWER'
export const SET_BIPINIT = "SET_BIPINIT"
export const CLEAN_BIPINIT = "CLEAN_BIPINIT"
export const UPDATE_UNLOCKED = "UPDATE_UNLOCKED"
