export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_CHAINID = 'UPDATE_CHAINID';
export const UPDATE_RDRAWER = 'UPDATE_RDRAWER';
export const SET_BIPINIT = 'SET_BIPINIT';
export const CLEAN_BIPINIT = 'CLEAN_BIPINIT';
export const UPDATE_ISUNLOCKED = 'UPDATE_ISUNLOCKED';
export const UPDATE_WALLET = 'UPDATE_WALLET';
export const UPDATE_SELECTEDADDRESS = 'UPDATE_SELECTEDADDRESS';

export const UPDATE_KEY = 'UPDATE_KEY';
export const SET_V3 = 'SET_V3';
export const SET_ENV3 = 'SET_ENV3';
export const SET_LOGINERROR = 'SET_LOGINERROR';
export const SET_LOGINLOADING = 'SET_LOGINLOADING';

export const SET_WALLET_OPEN = 'SET_WALLET_OPEN';
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';

export const SET_LIVE_ERROR = 'SET_LIVE_ERROR';
export const SET_LIVE_LOADING = 'SET_LIVE_LOADING';
export const UPDATE_GAS_PARAMS = 'UPDATE_GAS_PARAMS';
export const UPDATE_GAS_PARAMS_LOADING = 'UPDATE_GAS_PARAMS_LOADING';
