export const LOAD_ACTIVITY = 'LOAD_ACTIVITY';
export const UPDATE_LOCKED = 'UPDATE_LOCKED';
export const UPDATE_DRAWER = 'UPDATE_DRAWER';
export const UPDATE_CREATING_STATE = 'UPDATE_CREATING_STATE';
export const UPDATE_CREAT_ERROR = 'UPDATE_CREAT_ERROR';
export const UPDATE_UPDATE_PASSBOOK = 'UPDATE_UPDATE_PASSBOOK';
