export const UPDATE_ISUNLOCK = 'UPDATE_ISUNLOCK';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_SELECTED_ADDRESS = 'UPDATE_SELECTED_ADDRESS';
export const UPDATE_PLAIN = 'UPDATE_PLAIN';
export const UPDATE_TABID = 'UPDATE_TABID';
export const UPDATE_FILTER_HOST = 'UPDATE_FILTER_HOST';
export const UPDATE_FAVICON_URL = 'UPDATE_FAVICON_URL';
