export const UPDATE_LDRAWER = 'UPDATE_LDRAWER';
export const UPDATE_DENSE = 'UPDATE_DENSE';
export const UPDATE_MINI = 'UPDATE_MINI_VARIANT';
export const UPDATE_CURNAVS = 'UPDATE_CURNAVS';

export const SET_REMOTE_SAVING = 'SET_REMOTE_SAVING';
export const SET_REMOTE_ERROR = 'SET_REMOTE_ERROR';
export const SET_STEPID = 'SET_STEPID';
