export const UPDATE_IS_UNLOCKED = 'UPDATE_IS_UNLOCKED';
export const UPDATE_FAVICONURL = 'UPDATE_FAVICONURL';
export const UPDATE_TABID = 'UPDATE_TABID';
export const UPDATE_FILTER_HOST = 'UPDATE_FILTER_HOST';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';
